name: Build and Push to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to JFrog
      uses: JFrogDev/jfrog-cli-action@master
      with:
        server-id: 'cryptome2'
        url: 'cryptome2.jfrog.io/'
        username: 'devanshpatel22@gmail.com'
        password: ${{ secrets.JFROG_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t interview:latest .
        docker tag interview:latest cryptome2.jfrog.io/default-docker-virtual/interview:latest
        docker push cryptome2.jfrog.io/default-docker-virtual/interview:latest