name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Build the Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cryptome.jfrog.io/docker/interview:latest
          build-args: |
            NODE_VERSION=18.12.1
          
      # Publish the Docker image to JFrog Artifactory
      - name: Publish to JFrog Artifactory
        uses: JFrogDev/jfrog-cli-action@v1
        with:
          server-id: interview
          command: rt docker-push
          arguments: cryptome.jfrog.io/docker/interview:latest