name: Build and Push to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to JFrog
      uses: jfrog/setup-jfrog-cli@master
      with:
        server-id: 'cryptome2'
        url: 'https://cryptome2.jfrog.io/'
        username: 'devanshpatel22@gmail.com'
        password: ${{ secrets.JFROG_PASSWORD }}

    - name: Build, Push, and Run Docker image
      run: |
        docker login --username=devanshpatel22@gmail.com --password=${{ secrets.DOCKER_PASSWORD }} cryptome2.jfrog.io
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 429363805278.dkr.ecr.us-east-1.amazonaws.com
        docker build -t interview:latest .
        docker tag interview:latest cryptome2.jfrog.io/default-docker-virtual/interview:latest
        docker tag interview:latest 429363805278.dkr.ecr.us-east-1.amazonaws.com/interview:latest
        docker push cryptome2.jfrog.io/default-docker-virtual/interview:latest
        docker push 429363805278.dkr.ecr.us-east-1.amazonaws.com/interview:latest